### ISSUE TITLE
LCD GUI Update uploader missing

### ISSUE THREAD

**Issue by iwbnwif** [erainstruments/erasynth-micro-lcd-gui#1]
The updater software mentioned in the firmware update instructions is not available on Github.

**Comment by berjk** [comment]
GUI source code is not available on GitHub. 
The link in firmware update instructions document is valid.
Please check : https://github.com/erainstruments/erasynth-micro-lcd-gui/releases/download/v1.0.4/ERASynthMicroLCDGui.exe

**Comment by iwbnwif** [comment]
Thank you for the link - I am not sure why this didn't work before, but it is working fine now.
